version = 1

[[analyzers]]
name = "shell"

[[analyzers]]
name = "docker"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  environment = ["browser"]

[[code_formatters]]
name = "prettier"

[[code_formatters]]
name = "ruff"