"""Initial migration

Revision ID: d83305231d72
Revises:
Create Date: 2026-01-11 18:53:29.815213

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d83305231d72"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "raeume",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=6), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("modus", sa.String(length=20), nullable=False),
        sa.Column("erstellt_am", sa.DateTime(), nullable=True),
        sa.Column("spieler_anzahl", sa.Integer(), nullable=True),
        sa.Column("spiel_gestartet", sa.Boolean(), nullable=True),
        sa.Column("aktuelle_phase", sa.String(length=30), nullable=True),
        sa.Column("runde", sa.Integer(), nullable=True),
        sa.Column("erzaehler_id", sa.Integer(), nullable=True),
        sa.Column("erzaehler_modus", sa.String(length=20), nullable=True),
        sa.Column("spiel_beendet", sa.Boolean(), nullable=True),
        sa.Column("gewinner", sa.String(length=50), nullable=True),
        sa.Column("aktive_rollen", sa.Text(), nullable=True),
        sa.Column("timer_start", sa.DateTime(), nullable=True),
        sa.Column("timer_duration", sa.Integer(), nullable=True),
        sa.Column("phase_votes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["erzaehler_id"],
            ["spieler.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("raeume", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_raeume_code"), ["code"], unique=True)

    op.create_table(
        "spieler",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=30), nullable=False),
        sa.Column("session_id", sa.String(length=64), nullable=False),
        sa.Column("raum_id", sa.Integer(), nullable=True),
        sa.Column("rolle", sa.String(length=30), nullable=True),
        sa.Column("ist_am_leben", sa.Boolean(), nullable=True),
        sa.Column("ist_erzaehler", sa.Boolean(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.Column("beigetreten_am", sa.DateTime(), nullable=True),
        sa.Column("sitzplatz", sa.Integer(), nullable=True),
        sa.Column("rolle_zustand", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["raum_id"],
            ["raeume.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("spieler", schema=None) as batch_op:
        batch_op.create_index(
            "idx_spieler_raum_erzaehler", ["raum_id", "ist_erzaehler"], unique=False
        )
        batch_op.create_index(
            "idx_spieler_raum_leben", ["raum_id", "ist_am_leben"], unique=False
        )
        batch_op.create_index(
            "idx_spieler_raum_rolle", ["raum_id", "rolle"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_spieler_ist_am_leben"), ["ist_am_leben"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_spieler_raum_id"), ["raum_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_spieler_rolle"), ["rolle"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_spieler_session_id"), ["session_id"], unique=True
        )

    op.create_table(
        "aktionen",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("raum_id", sa.Integer(), nullable=False),
        sa.Column("runde", sa.Integer(), nullable=False),
        sa.Column("phase", sa.String(length=30), nullable=False),
        sa.Column("aktion_typ", sa.String(length=30), nullable=False),
        sa.Column("von_spieler_id", sa.Integer(), nullable=False),
        sa.Column("ziel_spieler_id", sa.Integer(), nullable=True),
        sa.Column("zusatz_daten", sa.Text(), nullable=True),
        sa.Column("zeitpunkt", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["raum_id"],
            ["raeume.id"],
        ),
        sa.ForeignKeyConstraint(
            ["von_spieler_id"],
            ["spieler.id"],
        ),
        sa.ForeignKeyConstraint(
            ["ziel_spieler_id"],
            ["spieler.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "erzaehler_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("raum_id", sa.Integer(), nullable=False),
        sa.Column("event_typ", sa.String(length=50), nullable=False),
        sa.Column("runde", sa.Integer(), nullable=True),
        sa.Column("ziel_spieler_ids", sa.String(length=100), nullable=True),
        sa.Column("gespielt_am", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["raum_id"],
            ["raeume.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "seherin_enthuellung",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("raum_id", sa.Integer(), nullable=False),
        sa.Column("seherin_id", sa.Integer(), nullable=False),
        sa.Column("ziel_id", sa.Integer(), nullable=False),
        sa.Column("enthuellung_typ", sa.String(length=20), nullable=False),
        sa.Column("gesehene_rolle", sa.String(length=50), nullable=True),
        sa.Column("runde", sa.Integer(), nullable=False),
        sa.Column("enthuellt_am", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["raum_id"],
            ["raeume.id"],
        ),
        sa.ForeignKeyConstraint(
            ["seherin_id"],
            ["spieler.id"],
        ),
        sa.ForeignKeyConstraint(
            ["ziel_id"],
            ["spieler.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("seherin_enthuellung", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_seherin_enthuellung_raum_id"), ["raum_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_seherin_enthuellung_seherin_id"),
            ["seherin_id"],
            unique=False,
        )

    op.create_table(
        "spieler_positionen",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("spieler_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["spieler_id"],
            ["spieler.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("spieler_id"),
    )
    op.create_table(
        "spiellog",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("raum_id", sa.Integer(), nullable=False),
        sa.Column("nachricht", sa.Text(), nullable=False),
        sa.Column("zeitpunkt", sa.DateTime(), nullable=True),
        sa.Column("sichtbar_fuer", sa.String(length=100), nullable=True),
        sa.ForeignKeyConstraint(
            ["raum_id"],
            ["raeume.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("spiellog")
    op.drop_table("spieler_positionen")
    with op.batch_alter_table("seherin_enthuellung", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_seherin_enthuellung_seherin_id"))
        batch_op.drop_index(batch_op.f("ix_seherin_enthuellung_raum_id"))

    op.drop_table("seherin_enthuellung")
    op.drop_table("erzaehler_events")
    op.drop_table("aktionen")
    with op.batch_alter_table("spieler", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_spieler_session_id"))
        batch_op.drop_index(batch_op.f("ix_spieler_rolle"))
        batch_op.drop_index(batch_op.f("ix_spieler_raum_id"))
        batch_op.drop_index(batch_op.f("ix_spieler_ist_am_leben"))
        batch_op.drop_index("idx_spieler_raum_rolle")
        batch_op.drop_index("idx_spieler_raum_leben")
        batch_op.drop_index("idx_spieler_raum_erzaehler")

    op.drop_table("spieler")
    with op.batch_alter_table("raeume", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_raeume_code"))

    op.drop_table("raeume")
    # ### end Alembic commands ###
