- name: PyAction: linter
  # You may pin to the exact commit or the version.
  # uses: rahul-deepsource/pyaction@9071389c6482762ea0132c23d431a8fe4aa7d0a1
  uses: rahul-deepsource/pyaction@1.4.1
  with:
    # A list of all paths to test
    python-root-list: # optional, default is ./**/*.py
    # Use Pylint
    use-pylint: # optional, default is true
    # Use pycodestyle
    use-pycodestyle: # optional, default is true
    # Use Flake8
    use-flake8: # optional, default is true
    # Use Black
    use-black: # optional, default is true
    # Use mypy
    use-mypy: # optional, default is true
    # Use isort
    use-isort: # optional, default is true
    # Use vulture
    use-vulture: # optional, default is true
    # Extra options: pylint $(extra-pylint-options) $(python-root-list)
    extra-pylint-options: # optional, default is 
    # Extra options: pycodestyle $(extra-pycodestyle-options) $(python-root-list)
    extra-pycodestyle-options: # optional, default is 
    # Extra options: flake8 $(extra-flake8-options) $(python-root-list)
    extra-flake8-options: # optional, default is 
    # Extra options: black --check $(extra-black-options) $(python-root-list)
    extra-black-options: # optional, default is 
    # Extra options: mypy $(extra-mypy-options) $(python-root-list)
    extra-mypy-options: # optional, default is 
    # Extra options: isort -rc $(extra-isort-options) $(python-root-list) -c --diff 
    extra-isort-options: # optional, default is 
    # Extra options: vulture $(extra-vulture-options) $(python-root-list)
    extra-vulture-options: # optional, default is 
