#workflow will run on push to Pro branch and on pull request to Pro branch
#it will run the following bash commands: 
# pip install sphinx sphinx-markdown-builder;
#sphinx-apidoc -o Sphinx-docs . sphinx-apidoc --full -A 'SpotlightForBugs'; cd Sphinx-docs;
# echo " import os
# import sys
# sys.path.insert(0,os.path.abspath('../'))
# def skip(app, what, name, obj,would_skip, options):
#     if name in ( '__init__',):
#         return False
#     return would_skip
# def setup(app):
#     app.connect('autodoc-skip-member', skip)
# extensions.append('sphinx_autodoc_typehints')
#  " >> conf.py;
# make markdown;
#mv _build/markdown/* ../; rm -r Sphinx-docs;


name: bash commands
on:
  push:
    branches: [ Pro ]
  pull_request:
    branches: [ Pro ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a multi-line script
        run: |
          pip install sphinx sphinx-markdown-builder
          pip install sphinx-autodoc-typehints
          sphinx-apidoc -o Sphinx-docs . sphinx-apidoc --full -A 'SpotlightForBugs'
          cd Sphinx-docs
          echo " 
          import os
          import sys
          sys.path.insert(0,os.path.abspath('../'))
          def skip(app, what, name, obj,would_skip, options):
              if name in ( '__init__',):
                  return False
              return would_skip
          def setup(app):
              app.connect('autodoc-skip-member', skip)
          extensions.append('sphinx_autodoc_typehints')
          " >> conf.py;
          make markdown


name: Create Pull Request
on:
  push:
    branches: [ Pro ]
  pull_request:
    branches: [ Pro ]
jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a multi-line script
        run: |
          mv _build/markdown/* ../; rm -rf _build
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add -A
          git commit -m "Update Markdown Documentation"
          git push
          git checkout Pro
          git merge master
          git push
          git checkout master
          git merge Pro
          git push
      - uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Update Markdown Documentation
          title: Update Markdown Documentation
          body: Update Markdown Documentation
          branch: Pro
          base: Pro
          labels: documentation
          


