#generate documenation for the  python files in the root directory and output to the file Documenation.md

name: Documentation

on:
  push:
    branches: [ pro ]
  pull_request:
    branches: [ pro ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pydoc-markdown
        pip install pydoc-markdown[linkcheck]
        pip install pydoc-markdown[coverage]
        pip install pydoc-markdown[mermaid]
    - name: Generate Documentation
      run: |
        pydocmd *.py > Documentation.md
    - name: Commit files
      run: |
        git config --local user.email 