name: documentation
on:
  push:
    branches: [ Pro ]
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a multi-line script
        run: |
          pip install -r requirements.txt
          pip install lazydocs
          lazydocs werwolf.py
          

          #create pull request
          
          
          git config --global user.email ""
          git config --global user.name "A lazy Bot"
          git add .
          git commit -m "We have updates for the documentation"
          git push





            


