name: documentation
on:
  push:
    branches: [ Pro ]
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a multi-line script
        run: |
          pip install -r requirements.txt
          pip install lazydocs
          lazydocs werwolf.py 
          lazydocs app.py 
          sleep 5
          mv werwolf.py.md werwolf.md
          mv app.py.md app.md
          git config --global user.email "
          git config --global user.name "github-actions[bot]"
          git add .
          git commit -m "Update documentation"
          git push
          

  
          




            


