name: documentation
on:
  push:
    branches: [ Pro ]
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a multi-line script
        run: |
          pip install -r requirements.txt
          pip install lazydocs
          lazydocs werwolf.py -o werwolf.md
          lazydocs app.py -o app.md


  
          




            


